## 2. Missing Value Estimation:
For the missing value estimation problem there were total three datasets. The first dataset contains 4% missing values, 2nd dataset contains 10% missing values and for the 3rd dataset almost 83% data are missing.

<center><b>Dataset</b></center>

| Dataset | Samples | Genes/Virus | Missing value % |
|---------|---------|-------------|-----------------|
|    1    |   242   |      14     |       4         |
|    2    |   758   |      50     |       10        |
|    3    |   272   |      79     |       83        |

__Hint:__
* Missing Value Estimation
* KNN method for imputation of the missing values
* Euclidian Distance Calculation
* Find the value of k and search for the optimal value of k

In [2]:
import gc
gc.collect()

22

In [3]:
# Supress warnings
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn

# Base packages
import gc, sys, re, os, re
from time import strptime, mktime
sys.setrecursionlimit(100000)

# Data processing packages
import numpy as np
import pandas as pd

# Testing & Validation packages
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import confusion_matrix, classification_report, roc_curve, roc_auc_score

# KNN
from sklearn.neighbors import KNeighborsClassifier
from impyute.imputation.cs import fast_knn

In [4]:
# Import data sets
md1 = pd.read_csv('data/2/MissingData1.txt', delimiter='\s+', header=None)
md2 = pd.read_csv('data/2/MissingData2.txt', delimiter='\s+', header=None)
md3 = pd.read_csv('data/2/MissingData3.txt', delimiter='\s+', header=None)

In [5]:
n = md1[2][3]
n

1.0000000000000001e+99

In [132]:
# Find all values in md1, md2, md3 that = 1.00000000000000e+99 & replace with NaN
for i in md1.keys():
    md1[i] = md1[i].replace(n, np.nan)
    
for i in md2.keys():
    md2[i] = md2[i].replace(n, np.nan)

for i in md3.keys():
    md3[i] = md3[i].replace(n, np.nan)

In [133]:
# Use fast_knn to fill NaN values in md1, md2, md3
md1 = fast_knn(md1.values, k=50)

In [134]:
# Turn into a DF and look at the top 10 rows

md1 = pd.DataFrame(md1)
md1.head(10)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,-0.11,0.02,-0.360000,-0.110000,0.480000,-0.200000,0.27,0.29,-0.340000,-0.05,0.23,0.08,-0.45,0.25
1,-0.30,-0.37,-0.180000,-0.090000,-0.160000,-0.160000,-0.10,-0.09,0.460000,0.32,0.02,0.31,0.40,-0.07
2,0.50,0.18,0.410000,0.047202,-0.000726,0.150000,-0.25,-0.41,-0.070000,-0.13,-0.15,-0.01,-0.28,-0.09
3,0.00,-0.11,-0.037132,0.190000,0.000000,-0.070000,0.18,0.18,-0.230000,-0.16,0.03,-0.12,-0.11,0.23
4,0.40,-0.16,0.310000,-0.340000,0.020000,0.210000,-0.70,0.11,0.080000,0.05,-0.09,0.07,0.04,-0.01
5,0.39,-0.18,-0.090000,-0.040000,-0.250000,-0.690000,-0.64,-0.38,0.410000,0.33,-0.62,0.23,0.92,0.61
6,0.50,-0.24,-0.160000,0.017974,0.040000,-0.030437,-0.11,0.10,-0.040000,-0.01,-0.04,-0.15,0.05,-0.11
7,-0.52,-0.48,-0.730000,-0.420000,-0.400000,-0.010000,-0.34,0.55,0.221421,0.37,-0.29,0.63,0.87,0.28
8,-0.87,-0.17,0.100000,-0.120000,0.099142,0.520000,-0.28,0.50,0.090000,-0.01,0.08,-0.15,-0.16,-0.16
9,-1.39,-0.57,-0.160000,-0.020000,0.300000,0.410000,0.03,0.50,0.480000,0.51,-0.11,0.14,-0.06,-0.05

In [135]:
md2 = fast_knn(md2.values, k=50)

In [136]:
md2 = pd.DataFrame(md2)

md2.head(10)

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,0.688728,-0.212720,0.498783,0.836527,0.753066,-0.212667,0.942724,-0.452367,-0.077101,0.223916,...,0.179593,0.694768,0.617762,-0.040676,0.067808,0.032745,0.701679,0.272815,0.242996,0.044602
1,0.276757,0.110242,-0.219114,-0.007928,-0.126895,0.312428,0.205479,0.228858,0.290239,0.152407,...,-0.231804,-0.004617,-0.483945,-0.056103,-0.324140,-0.152420,-0.259235,-0.152041,-0.487165,-0.600970
2,-0.738929,-0.109915,-0.584726,0.184901,-0.124804,-0.182223,0.106920,-0.280529,0.160430,-0.379498,...,-0.278944,-0.178492,-0.109231,-0.030136,-0.276224,-0.152208,-0.222567,-0.089719,-0.180418,-0.235246
3,0.245575,-0.073991,-0.317213,-0.238237,-0.234355,-0.455127,-0.326878,-0.493662,-0.123100,-0.380940,...,0.353774,0.285639,0.233876,0.088700,-0.025839,-0.322532,0.433586,0.323603,0.360877,0.236961
4,0.239510,0.029406,0.283365,0.047755,0.235801,0.002013,0.474516,-0.216095,-0.247166,0.167056,...,0.237784,0.439557,-0.006479,-0.157518,-0.014099,0.063090,0.761268,0.321644,0.199316,-0.023753
5,-0.869971,0.399930,-0.366042,-0.624458,-0.138599,-0.154926,-0.561274,-0.125091,0.059304,-0.471087,...,0.575654,0.040567,-0.248149,0.101134,0.468096,0.176674,0.238402,0.334943,0.359518,0.457162
6,0.572017,0.340113,0.029873,0.578126,0.197955,0.142759,0.919904,0.036152,0.486209,0.391493,...,0.052258,0.607901,0.144501,-0.153071,-0.008045,0.235935,0.432677,0.137041,0.307290,-0.397008
7,-0.268840,0.055739,-0.395090,-0.028300,0.075139,0.097813,0.023466,0.070807,0.583128,0.088929,...,0.167470,0.728633,0.314193,-0.145255,0.007313,0.065286,0.678722,0.222878,0.262801,-0.130599
8,0.361593,0.233411,0.418191,0.640645,0.589923,0.196333,1.159427,0.053868,0.457143,0.556191,...,0.255668,0.906470,0.636472,0.009617,0.158082,-0.206306,0.753817,0.358834,0.363250,-0.090398
9,-0.623860,-0.438771,-0.388759,-0.092083,-0.276050,-0.167775,0.064051,-0.573183,-0.479844,-0.373068,...,-1.453067,-0.521849,-0.766912,-0.032689,-0.183648,-0.116656,-0.481913,-0.209040,0.412279,0.045084

In [137]:
md3 = fast_knn(md3.values, k=50)

In [138]:
md3 = pd.DataFrame(md3)
md3.head(10)

,0,1,2,3,4,5,6,7,8,9,...,69,70,71,72,73,74,75,76,77,78
0,10.145677,4.357071,6.374937,8.646739,7.446256,6.89985,7.415527,6.655352,6.602659,6.001754,...,7.375625,9.664946,10.079145,10.758123,9.812527,10.668332,7.675157,10.715034,9.158564,9.033972
1,11.000000,4.357071,6.467395,8.000000,7.000000,10.00000,6.000000,6.000000,6.742032,4.000000,...,7.369214,9.659395,10.076569,10.754607,9.808048,10.665874,7.684108,10.713990,9.163702,9.033227
2,11.861707,4.357071,6.374938,7.559956,8.862947,6.89985,7.313518,7.469635,5.000000,5.000000,...,7.375020,9.668846,10.094689,10.781869,9.845039,10.683906,7.661507,10.716101,9.164803,9.102050
3,11.999000,10.000000,6.374938,11.000000,6.405992,6.89985,4.000000,7.533209,4.000000,6.268299,...,7.318298,9.499124,10.004719,10.686944,9.708347,10.607180,7.932594,10.697560,9.336789,8.959841
4,10.000000,4.357071,6.374937,9.000000,7.584963,6.89985,7.000000,8.000000,6.856803,6.321280,...,7.378091,9.647217,10.080380,10.767028,9.834918,10.668382,7.672285,10.709098,9.170963,9.098368
5,11.999000,4.357071,6.374937,9.000000,7.836723,6.89985,6.000000,6.510962,5.000000,5.000000,...,7.374780,9.670403,10.095638,10.782954,9.845993,10.684936,7.660369,10.716529,9.164195,9.102615
6,10.791814,4.357071,6.374938,8.501439,7.498251,6.89985,6.070389,6.201634,5.000000,5.000000,...,7.374400,9.672824,10.083461,10.762907,9.816438,10.673061,7.669579,10.717169,9.155135,9.034707
7,11.793116,4.357071,6.374938,9.000000,8.174907,6.89985,6.510962,6.201634,5.000000,5.000000,...,7.373907,9.675973,10.098981,10.786856,9.849575,10.688565,7.656026,10.718011,9.161897,9.104870
8,10.000000,4.357071,6.374937,8.000000,7.000000,6.89985,5.263034,6.201634,5.000000,5.000000,...,7.374315,9.673400,10.097460,10.785043,9.847845,10.686913,7.658154,10.717347,9.163013,9.103722
9,9.044394,4.357071,6.374938,8.292782,6.510962,6.89985,7.383529,5.807355,5.000000,5.000000,...,7.373809,9.676597,10.085500,10.765186,9.818341,10.675296,7.666830,10.718174,9.153448,9.035079